export const ADD_INGREDIENT = 'ADD_INGREDIENT'
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT'
export const SET_INGREDIENTS_SUCCESS = 'SET_INGREDIENTS_SUCCESS'
export const SET_INGREDIENTS_FAILED = 'SET_INGREDIENTS_FAILED'

export const PURCHASE_BURGER_INIT = 'PURCHASE_BURGER_INIT'
export const PURCHASE_BURGER_LOADING = 'PURCHASE_BURGER_LOADING'
export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS'
export const PURCHASE_BURGER_FAILED = 'PURCHASE_BURGER_FAILED'

export const FETCH_ORDERS_LOADING = 'FETCH_ORDERS_LOADING'
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS'
export const FETCH_ORDERS_FAILED = 'FETCH_ORDERS_FAILED'

export const AUTHENTICATION_LOADING = 'AUTHENTICATION_LOADING'
export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS'
export const AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED'
export const AUTHENTICATION_LOGOUT = 'AUTHENTICATION_LOGOUT'

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH'

export const TRY_DELETE_ORDER = 'TRY_DELETE_ORDER'
export const DELETE_ORDER_SUCCESS = 'DELETE_ORDER_SUCCESS'
export const DELETE_ORDER_FAILED = 'DELETE_ORDER_FAILED'
